const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('es-PE').format(Number(n)||0);
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Set','Oct','Nov','Dic'];
let data=INITIAL_DATA, meta=INITIAL_META, orgSelected=null, expanded=new Set();
try{data=JSON.parse(localStorage.getItem('exp_data'))||INITIAL_DATA;meta=JSON.parse(localStorage.getItem('exp_meta'))||INITIAL_META}catch{}
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const sum=d=>d.reduce((a,x)=>a+(+x.cantidad||0),0);
const scopeOf=x=>String(x.ambito||'DRELM').toUpperCase()==='UGEL'?'UGEL':'DRELM';
const uniq=(d,k)=>[...new Set(d.map(x=>clean(x[k])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const meaningful=(v)=>{v=clean(v);return v&&v!=='DIRECCIÓN'&&v!=='DRELM'};
function firstMeaningfulKey(scope,d){for(const k of ['oficina','unidad','area','subarea']){if(d.some(x=>meaningful(x[k])))return k}return 'oficina'}
function summaryKey(d){const sc=$('#fScope').value;if(sc)return firstMeaningfulKey(sc,d);return 'ambito'}
function aggDynamic(d){const sc=$('#fScope').value;if(!sc){const M={};d.forEach(x=>{let k=scopeOf(x);M[k]??={p:0,e:0,ys:{}};if(x.estado==='POR RECIBIR')M[k].p+=x.cantidad;else M[k].e+=x.cantidad;M[k].ys[x.anio]=(M[k].ys[x.anio]||0)+x.cantidad});return Object.entries(M).map(([k,v])=>({k,...v,t:v.p+v.e,rez:(v.ys[2023]||0)+(v.ys[2024]||0)+(v.ys[2025]||0)})).sort((a,b)=>b.t-a.t)}return agg(d,firstMeaningfulKey(sc,d)).filter(x=>meaningful(x.k))}
function initFilters(){
  const ys=[...new Set(data.map(x=>x.anio))].sort();
  $('#fYear').innerHTML='<option value="">Todos los años</option>'+ys.map(y=>`<option>${y}</option>`).join('');
  $('#fMonth').innerHTML='<option value="">Todos los meses</option>'+months.map((m,i)=>`<option value="${i+1}">${m}</option>`).join('');
}
function filtered(){const sc=$('#fScope').value,st=$('#fState').value,y=$('#fYear').value,m=$('#fMonth').value;return data.filter(x=>(!sc||scopeOf(x)===sc)&&(!st||x.estado===st)&&(!y||x.anio===+y)&&(!m||x.mes===+m))}
function agg(d,key='oficina'){const M={};d.forEach(x=>{let k=clean(x[key])||'Sin dependencia';M[k]??={p:0,e:0,ys:{}};if(x.estado==='POR RECIBIR')M[k].p+=x.cantidad;else M[k].e+=x.cantidad;M[k].ys[x.anio]=(M[k].ys[x.anio]||0)+x.cantidad});return Object.entries(M).map(([k,v])=>({k,...v,t:v.p+v.e,rez:(v.ys[2023]||0)+(v.ys[2024]||0)+(v.ys[2025]||0)})).sort((a,b)=>b.t-a.t)}
function renderSummary(){const d=filtered(),total=sum(d),pr=sum(d.filter(x=>x.estado==='POR RECIBIR')),ep=total-pr,ys=[...new Set(d.map(x=>x.anio))].sort();
 $('#kTotal').textContent=fmt(total);$('#kReceive').textContent=fmt(pr);$('#kProcess').textContent=fmt(ep);$('#pReceive').textContent=total?`${(pr/total*100).toFixed(1)}% del total`:'0%';$('#pProcess').textContent=total?`${(ep/total*100).toFixed(1)}% del total`:'0%';let sk=summaryKey(d);$('#kDeps').textContent=fmt(sk==='ambito'?[...new Set(d.map(scopeOf))].length:uniq(d,sk).filter(meaningful).length);$('#kYears').textContent=ys.length;$('#yearsText').textContent=ys.join(', ')||'-';$('#lastUpdate').textContent=`${meta.fecha||'-'} ${meta.hora||''}`;
 // ámbito: al filtrar un ámbito, el centro y la leyenda reflejan la selección real
 const scopes={DRELM:sum(d.filter(x=>scopeOf(x)==='DRELM')),UGEL:sum(d.filter(x=>scopeOf(x)==='UGEL'))};let dp=total?scopes.DRELM/total*100:0;$('#scopeDonut').style.background=`conic-gradient(#1677d2 0 ${dp}%,#f59e0b ${dp}% 100%)`;$('#scopeTotal').textContent=fmt(total);$('#scopeLegend').innerHTML=['DRELM','UGEL'].map((s,i)=>`<div class="leg"><i class="dot" style="background:${i?'#f59e0b':'#1677d2'}"></i><b>${s}</b><span>${fmt(scopes[s])} (${total?(scopes[s]/total*100).toFixed(1):0}%)</span></div>`).join('');
 let pp=total?ep/total*100:0;$('#donutTotal').textContent=fmt(total);$('#stateDonut').style.background=`conic-gradient(#1688df 0 ${pp}%,#ff3150 ${pp}% 100%)`;$('#stateLegend').innerHTML=`<div class="leg"><i class="dot" style="background:#1688df"></i><b>En proceso</b><span>${fmt(ep)} (${total?(ep/total*100).toFixed(1):0}%)</span></div><div class="leg"><i class="dot" style="background:#ff3150"></i><b>Por recibir</b><span>${fmt(pr)} (${total?(pr/total*100).toFixed(1):0}%)</span></div>`;
 let mm=Array(12).fill(0);d.forEach(x=>mm[x.mes-1]+=x.cantidad);let mx=Math.max(...mm,1);$('#monthChart').innerHTML=mm.map((v,i)=>`<div class="col"><div class="colbar" data-v="${fmt(v)}" style="height:${Math.max(2,v/mx*190)}px"></div><label>${months[i]}</label></div>`).join('');
 const colors=['#18b77b','#4294ef','#f2b820','#f0354c','#8c5de7'];let ym={};d.forEach(x=>ym[x.anio]=(ym[x.anio]||0)+x.cantidad);let ya=Object.entries(ym).sort((a,b)=>b[0]-a[0]),acc=0,parts=[];ya.forEach(([y,v],i)=>{let p=total?v/total*100:0;parts.push(`${colors[i%colors.length]} ${acc}% ${acc+p}%`);acc+=p});$('#yearTotal').textContent=fmt(total);$('#yearDonut').style.background=`conic-gradient(${parts.join(',')||'#ddd 0 100%'})`;$('#yearLegend').innerHTML=ya.map(([y,v],i)=>`<div class="leg"><i class="dot" style="background:${colors[i%colors.length]}"></i><b>${y}</b><span>${fmt(v)} (${total?(v/total*100).toFixed(1):0}%)</span></div>`).join('');
 let old={2023:0,2024:0,2025:0};d.forEach(x=>{if(x.anio in old)old[x.anio]+=x.cantidad});let om=Math.max(...Object.values(old),1);$('#top5').innerHTML=Object.entries(old).map(([y,v])=>`<div class="toprow"><b>${y}</b><div class="miniTrack"><div class="miniFill" style="width:${v/om*100}%"></div></div><strong>${fmt(v)}</strong></div>`).join('')+`<div class="backlogTotal"><span>Total rezago</span><b>${fmt(Object.values(old).reduce((a,b)=>a+b,0))}</b></div>`;
 let rows=aggDynamic(d).filter(x=>x.k.toLowerCase().includes($('#search').value.toLowerCase()));$('#tbody').innerHTML=rows.map((x,i)=>{let oldest=[2023,2024,2025,2026].find(y=>x.ys[y]>0),lab=oldest===2023?'Crítico':oldest===2024?'Alto':oldest===2025?'Atención':'Al día',cls=oldest<=2024?'red':oldest===2025?'amber':'green';return `<tr><td>${i+1}</td><td><b>${x.k}</b></td><td class="num">${fmt(x.p)}</td><td class="num">${fmt(x.e)}</td><td class="num"><b>${fmt(x.t)}</b></td><td class="num">${total?(x.t/total*100).toFixed(1):0}%</td><td class="num">${fmt(x.rez)}</td><td><span class="pill ${cls}">${lab}</span></td></tr>`}).join('')||'<tr><td colspan="8">Sin resultados</td></tr>';
}
function depData(){let d=filtered();if(!orgSelected)return d;return d.filter(x=>{if(scopeOf(x)!==orgSelected.scope)return false;return orgSelected.path.every(p=>clean(x[p.key])===p.value)})}
function availableKeys(scope,d,path=[]){let preferred=['oficina','unidad','area','subarea'];let used=new Set(path.map(p=>p.key));return preferred.filter(k=>!used.has(k)&&d.some(x=>meaningful(x[k])))}
function nextKey(scope,path){let d=filtered().filter(x=>scopeOf(x)===scope);path.forEach(p=>d=d.filter(x=>clean(x[p.key])===p.value));return availableKeys(scope,d,path)[0]||null}
function children(scope,path){let d=filtered().filter(x=>scopeOf(x)===scope);path.forEach(p=>d=d.filter(x=>clean(x[p.key])===p.value));let key=nextKey(scope,path);if(!key)return[];let vals={};d.forEach(x=>{let v=clean(x[key]);if(v&&v!=='DIRECCIÓN'&&v!=='DRELM'){if(!vals[v])vals[v]={total:0,e:0,p:0};vals[v].total+=x.cantidad;if(x.estado==='EN PROCESO')vals[v].e+=x.cantidad;else if(x.estado==='POR RECIBIR')vals[v].p+=x.cantidad}});return Object.entries(vals).map(([value,z])=>({scope,path:[...path,{key,value}],label:value,total:z.total,e:z.e,p:z.p,key})).sort((a,b)=>b.total-a.total)}
const nodeId=n=>n.scope+'|'+n.path.map(p=>p.key+':'+p.value).join('|');
function nodeRows(n,depth,max){let kids=children(n.scope,n.path),id=nodeId(n),open=expanded.has(id),sel=orgSelected&&nodeId(orgSelected)===id,tot=n.total||1,pp=tot?n.e/tot*100:0,rp=tot?n.p/tot*100:0;let html=`<div class="depnode ${sel?'selected':''}" data-scope="${n.scope}" data-path="${encodeURIComponent(JSON.stringify(n.path))}" style="--depth:${depth}"><button class="treeexp" ${kids.length?'':'disabled'}>${kids.length?(open?'−':'+'):'•'}</button><button class="treeselect" title="En proceso: ${fmt(n.e)} (${pp.toFixed(1)}%) · Por recibir: ${fmt(n.p)} (${rp.toFixed(1)}%) · Total: ${fmt(n.total)}"><span class="treelabel">${n.label}<small class="treecounts"><em class="tc-proc">En proceso ${fmt(n.e)}</em><em class="tc-recv">Por recibir ${fmt(n.p)}</em><em class="tc-total">Total ${fmt(n.total)}</em></small></span><span class="stack"><i class="proc" style="width:${pp}%" title="En proceso: ${fmt(n.e)} (${pp.toFixed(1)}%)"></i><i class="recv" style="width:${rp}%" title="Por recibir: ${fmt(n.p)} (${rp.toFixed(1)}%)"></i></span><span class="treevalues"><b class="tv-proc">${fmt(n.e)}</b><b class="tv-recv">${fmt(n.p)}</b><strong>${fmt(n.total)}</strong></span></button></div>`;if(open&&kids.length){let km=Math.max(...kids.map(z=>z.total),1);html+=kids.map(k=>nodeRows(k,depth+1,km)).join('')}return html}
function rootsForCurrent(){let d=filtered(),sc=$('#fScope').value;if(sc){let rows=children(sc,[]);return rows.length?rows:[{scope:sc,path:[],label:sc,total:sum(d.filter(x=>scopeOf(x)===sc)),e:sum(d.filter(x=>scopeOf(x)===sc&&x.estado==='EN PROCESO')),p:sum(d.filter(x=>scopeOf(x)===sc&&x.estado==='POR RECIBIR'))}]}
return ['DRELM','UGEL'].map(scope=>{let sd=d.filter(x=>scopeOf(x)===scope);return {scope,path:[],label:scope,total:sum(sd),e:sum(sd.filter(x=>x.estado==='EN PROCESO')),p:sum(sd.filter(x=>x.estado==='POR RECIBIR'))}}).filter(x=>x.total)}
function renderTree(){let roots=rootsForCurrent();let mx=Math.max(...roots.map(x=>x.total),1);$('#orgBreadcrumb').innerHTML=`<button class="crumb ${!orgSelected?'active':''}" id="treeAll">Todos</button>${orgSelected?`<span class="treepath">› ${orgSelected.scope}${orgSelected.path.map(p=>' › '+p.value).join('')}</span>`:''}`;$('#depBars').innerHTML=roots.length?roots.map(r=>nodeRows(r,0,mx)).join(''):'<div class="hierarchy-message">No hay información para los filtros seleccionados.</div>';$('#treeAll').onclick=()=>{orgSelected=null;renderDependencias()};$$('#depBars .depnode').forEach(el=>{let n={scope:el.dataset.scope,path:JSON.parse(decodeURIComponent(el.dataset.path))},id=nodeId(n);el.querySelector('.treeexp').onclick=e=>{e.stopPropagation();expanded.has(id)?expanded.delete(id):expanded.add(id);renderTree()};el.querySelector('.treeselect').onclick=()=>{orgSelected=n;expanded.add(id);renderDependencias()}})}
function levelLabel(k,scope){if(scope==='UGEL'){if(k==='unidad')return 'Áreas UGEL';if(k==='area')return 'Equipos / niveles internos';if(k==='subarea')return 'Subáreas / servicios';return 'Dependencias UGEL'}if(k==='oficina')return 'Oficinas';if(k==='unidad')return 'Unidades';if(k==='area')return 'Áreas / Equipos';return 'Subáreas / Equipos'}
function renderDependencias(){let base=filtered(),sc=$('#fScope').value,st=$('#fState').value,y=$('#fYear').value,m=$('#fMonth').value;$('#activeFilters').innerHTML=`<b>Filtros aplicados:</b><span>Ámbito: ${sc||'Todos'}</span><span>Estado: ${st||'Todos'}</span><span>Año: ${y||'Todos'}</span><span>Mes: ${m?months[+m-1]:'Todos'}</span>`;let d=depData(),total=sum(d),scope=orgSelected?.scope||sc||'';let cards=[['Total',total]];if(scope){let keys=availableKeys(scope,d,[]);keys.forEach(k=>cards.push([levelLabel(k,scope),uniq(d,k).filter(v=>v&&v!=='DIRECCIÓN').length]))}else{cards.push(['DRELM',sum(d.filter(x=>scopeOf(x)==='DRELM'))],['UGEL',sum(d.filter(x=>scopeOf(x)==='UGEL'))])}$('#structureSummary').innerHTML=cards.filter((x,i)=>i===0||x[1]>0).map(([k,v])=>`<div><span>${k}</span><strong>${fmt(v)}</strong></div>`).join('');$('#depTitle').textContent=`${scope||'Todos los ámbitos'} · Composición por estado`;$('#depSubtitle').textContent='Cada barra conserva En proceso / Por recibir y permite desplegar el siguiente nivel.';$('#scopeKey').textContent=scope?`Ámbito: ${scope}`:'Ámbitos: DRELM y UGEL';$('#scopeKey').className='scope-key '+(scope==='UGEL'?'ugel':scope==='DRELM'?'drelm':'');renderTree();$('#hierarchy').innerHTML=orgSelected?`<b>Selección:</b> ${orgSelected.scope}${orgSelected.path.map(p=>' → '+p.value).join('')}`:'<b>Selección:</b> Todos';}
function renderEvolucion(){let d=filtered(),arr=months.map((m,i)=>({m,p:sum(d.filter(x=>x.mes===i+1&&x.estado==='POR RECIBIR')),e:sum(d.filter(x=>x.mes===i+1&&x.estado==='EN PROCESO'))})),mx=Math.max(...arr.map(x=>x.p+x.e),1);$('#evoChart').innerHTML=arr.map(x=>{let t=x.p+x.e,h=Math.max(8,t/mx*230),ep=t?x.e/t*100:0,rp=t?x.p/t*100:0;return `<div class="evocol"><div class="evovalue">${fmt(t)}</div><div class="evostack" style="height:${h}px" title="En proceso: ${fmt(x.e)} · Por recibir: ${fmt(x.p)} · Total: ${fmt(t)}"><i class="evoproc" style="height:${ep}%"></i><i class="evorecv" style="height:${rp}%"></i></div><div class="evometa"><span>● ${fmt(x.e)}</span><span>● ${fmt(x.p)}</span></div><b>${x.m}</b></div>`}).join('');let ym={};d.forEach(x=>ym[x.anio]=(ym[x.anio]||0)+x.cantidad);let yt=sum(d);$('#yearCards').innerHTML=Object.entries(ym).sort((a,b)=>b[0]-a[0]).map(([y,v])=>`<div class="yearcard"><span>${y}</span><strong>${fmt(v)}</strong><small>${yt?(v/yt*100).toFixed(1):0}% del total</small></div>`).join('')||'<p>Sin datos.</p>';$('#peakMonths').innerHTML=[...arr].sort((a,b)=>(b.p+b.e)-(a.p+a.e)).slice(0,6).map((x,i)=>{let t=x.p+x.e;return `<div class="peakrow"><b>${i+1}. ${x.m}</b><div class="peaktrack"><i class="peakfill" style="width:${t/mx*100}%"></i></div><strong>${fmt(t)}</strong><small>En proceso ${fmt(x.e)} · Por recibir ${fmt(x.p)}</small></div>`}).join('')}
function renderAntiguedad(){let d=filtered();[2023,2024,2025,2026].forEach(y=>$('#age'+y).textContent=fmt(sum(d.filter(x=>x.anio===y))));let rows=agg(d).filter(x=>x.rez>0).sort((a,b)=>b.rez-a.rez),mx=Math.max(...rows.map(x=>x.rez),1);$('#backlogDeps').innerHTML=rows.slice(0,20).map(x=>`<div class="backrow"><b>${x.k}</b><div class="miniTrack"><div class="miniFill" style="width:${x.rez/mx*100}%"></div></div><strong>${fmt(x.rez)}</strong></div>`).join('')||'<p>Sin rezago.</p>';let total=sum(d);$('#ageYears').innerHTML=[2023,2024,2025,2026].map(y=>{let v=sum(d.filter(x=>x.anio===y));return `<div class="agerow"><b>${y}</b><span>${fmt(v)}</span><strong>${total?(v/total*100).toFixed(1):0}%</strong></div>`}).join('')}
function renderDetalle(){let d=filtered(),q=$('#detailSearch').value.toLowerCase();d=d.filter(x=>[x.ambito,x.oficina,x.unidad,x.area,x.subarea,x.estado].join(' ').toLowerCase().includes(q));$('#detailCount').textContent=`${fmt(d.length)} registros consolidados · ${fmt(sum(d))} documentos`;$('#detailBody').innerHTML=d.slice(0,1500).map(x=>`<tr><td>${scopeOf(x)}</td><td>${x.oficina||'-'}</td><td>${x.unidad||'-'}</td><td>${x.area||'-'}</td><td>${x.subarea||'-'}</td><td>${x.estado}</td><td>${months[x.mes-1]}</td><td>${x.anio}</td><td class="num">${fmt(x.cantidad)}</td></tr>`).join('')}
function renderActualizacion(){let d=filtered();$('#metaFile').textContent=meta.archivo||'-';$('#metaDate').textContent=`${meta.fecha||'-'} ${meta.hora||''}`;$('#metaRows').textContent=fmt(data.length);$('#metaTotal').textContent=fmt(sum(data));}
function renderActive(){let v=$('.view.active')?.id?.replace('view-','')||'resumen';if(v==='resumen')renderSummary();if(v==='dependencias')renderDependencias();if(v==='evolucion')renderEvolucion();if(v==='detalle')renderDetalle();if(v==='actualizacion')renderActualizacion();$('#lastUpdate').textContent=`${meta.fecha||'-'} ${meta.hora||''}`}
function renderAll(){renderSummary();renderActive()}
function cellLooksRed(cell){if(!cell?.s?.font?.color)return false;let c=cell.s.font.color,rgb=String(c.rgb||'').replace(/^FF/i,'').toUpperCase();return ['FF0000','C00000','9C0006','E60000'].includes(rgb)||c.indexed===10}
function parseWorkbook(wb,name){let ws=wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(ws,{header:1,defval:null});if(a.length<27)throw Error('El archivo no tiene la estructura esperada del Reporte Genérico ESINAD.');let lv=['','','',''],state='',scope='DRELM',out=[];const cols=[0,2,4,8];for(let r=26;r<a.length;r++){let row=a[r];for(let i=0;i<4;i++){let t=clean(row[cols[i]]);if(t&&t!=='TOTAL'){let red=cellLooksRed(ws[XLSX.utils.encode_cell({r,c:cols[i]})]);lv[i]=t;for(let j=i+1;j<4;j++)lv[j]='';if(i===0)scope=red?'UGEL':'DRELM';if(red)scope='UGEL'}}let st=clean(row[11]);if(['POR RECIBIR','EN PROCESO'].includes(st))state=st;let m=+row[13];if(m>=1&&m<=12&&state){[[14,2023],[15,2024],[16,2025],[18,2026]].forEach(([c,y])=>{let q=+row[c];if(Number.isFinite(q)&&q>0)out.push({ambito:scope,oficina:lv[0],unidad:lv[1],area:lv[2],subarea:lv[3],estado:state,mes:m,anio:y,cantidad:q})})}}if(!out.length)throw Error('No se encontraron registros válidos.');return {out,meta:{fecha:clean(a[3]?.[17])||new Date().toLocaleDateString('es-PE'),hora:clean(a[5]?.[17])||new Date().toLocaleTimeString('es-PE'),archivo:name,registros:out.length}}}
async function loadFile(file){try{$('#uploadInfo').innerHTML='Procesando…';let wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellStyles:true}),res=parseWorkbook(wb,file.name);data=res.out;meta=res.meta;localStorage.setItem('exp_data',JSON.stringify(data));localStorage.setItem('exp_meta',JSON.stringify(meta));orgSelected=null;expanded.clear();initFilters();renderAll();$('#uploadInfo').innerHTML=`<p class="ok">✓ Base actualizada: ${fmt(sum(data))} documentos.</p>`}catch(e){$('#uploadInfo').innerHTML=`<p class="err">${e.message}</p>`}}
// navegación
$$('.navbtn').forEach(b=>b.onclick=()=>{$$('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+b.dataset.view).classList.add('active');renderActive()});
['#fScope','#fState','#fYear','#fMonth'].forEach(s=>$(s).onchange=()=>{orgSelected=null;renderAll()});$('#clearBtn').onclick=()=>{['#fScope','#fState','#fYear','#fMonth'].forEach(s=>$(s).value='');orgSelected=null;expanded.clear();renderAll()};$('#search').oninput=renderSummary;$('#detailSearch').oninput=renderDetalle;$('#orgHome').onclick=()=>{orgSelected=null;expanded.clear();renderDependencias()};
$('#exportBtn').onclick=()=>{let d=filtered();let rows=d.map(x=>({'Ámbito':scopeOf(x),'Oficina':x.oficina||'','Unidad':x.unidad||'','Área':x.area||'','Subárea':x.subarea||'','Estado':x.estado||'','Mes':months[(+x.mes||1)-1]||x.mes,'Año':x.anio,'Cantidad':x.cantidad}));let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:12},{wch:42},{wch:42},{wch:48},{wch:48},{wch:16},{wch:10},{wch:10},{wch:14}];XLSX.utils.book_append_sheet(wb,ws,'Detalle');let total=sum(d),resume=[['REPORTE DE SEGUIMIENTO DE EXPEDIENTES - ESINAD'],['Filtros aplicados'],['Ámbito',$('#fScope').value||'Todos'],['Estado',$('#fState').value||'Todos'],['Año',$('#fYear').value||'Todos'],['Mes',$('#fMonth').value?months[+$('#fMonth').value-1]:'Todos'],[],['Indicador','Cantidad'],['Total',total],['En proceso',sum(d.filter(x=>x.estado==='EN PROCESO'))],['Por recibir',sum(d.filter(x=>x.estado==='POR RECIBIR'))],['DRELM',sum(d.filter(x=>scopeOf(x)==='DRELM'))],['UGEL',sum(d.filter(x=>scopeOf(x)==='UGEL'))]];let wr=XLSX.utils.aoa_to_sheet(resume);wr['!cols']=[{wch:34},{wch:22}];XLSX.utils.book_append_sheet(wb,wr,'Resumen');XLSX.writeFile(wb,'seguimiento_expedientes_esinad.xlsx')};
$('#depExportBtn').onclick=()=>{let d=depData();let sc=orgSelected?.scope||$('#fScope').value||'';let path=orgSelected?.path||[];if(sc)d=d.filter(x=>scopeOf(x)===sc);path.forEach(p=>d=d.filter(x=>clean(x[p.key])===p.value));let keys=sc?availableKeys(sc,d,path):[];let key=keys[0]||firstMeaningfulKey(sc||'DRELM',d);let rows=agg(d,key).filter(x=>meaningful(x.k)).map(x=>({'Ámbito':sc||'Todos','Nivel':levelLabel(key,sc||'DRELM'),'Dependencia':x.k,'En proceso':x.e,'Por recibir':x.p,'Total':x.t,'Participación %':sum(d)?+(x.t/sum(d)*100).toFixed(1):0,'Rezago 2023-2025':x.rez}));let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:12},{wch:26},{wch:58},{wch:14},{wch:14},{wch:14},{wch:16},{wch:20}];XLSX.utils.book_append_sheet(wb,ws,'Dependencias');let filtros=[['REPORTE POR DEPENDENCIAS - ESINAD'],['Ámbito',sc||'Todos'],['Estado',$('#fState').value||'Todos'],['Año',$('#fYear').value||'Todos'],['Mes',$('#fMonth').value?months[+$('#fMonth').value-1]:'Todos'],['Selección jerárquica',path.map(x=>x.value).join(' > ')||'Nivel inicial'],[],['Total',sum(d)]];let wf=XLSX.utils.aoa_to_sheet(filtros);wf['!cols']=[{wch:26},{wch:60}];XLSX.utils.book_append_sheet(wb,wf,'Filtros');XLSX.writeFile(wb,'dependencias_esinad.xlsx')};
$('#uploadBtn').onclick=()=>$('#modal').classList.add('show');$('#uploadBtn2').onclick=()=>$('#modal').classList.add('show');$('#closeModal').onclick=()=>$('#modal').classList.remove('show');$('#drop').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])loadFile(e.dataTransfer.files[0])};
initFilters();renderAll();
